version: '3.1'

services:
  manager:
    build:
      context: .
      dockerfile: ./manager/Dockerfile
    environment:
      - MANAGER=true
    ports:
      - 8080:8080
  workers:
    depends_on:
      - manager
    build:
      context: .
      dockerfile: ./workers/Dockerfile
    environment:
      - UPLINK=manager:8081
